name: 'C++ CI'

on:
  push

jobs:
  build: 
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Init
        run: cmake . -DPATCH_VERSION=${{ github.run_number }}

      - name: Build
        run: cmake --build . 

      - name: test
        run: dir 

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lab-${{ runner.os }}
          path: build/lab && build/Release/lab.exe
      
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v4    
        with:
          path: artifact

      - run: dir

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/lab-Linux/lab
            artifacts/lab-Windows/lab.exe
          tag_name: 1.0.${{ github.run_number }}
          body: "Release 1.0.${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
