name: 'C++ CI'

on:
  push

jobs:
  build: 
    runs-on: ${{ matrix.os }}
    strategy:
      martix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v5

      - name: Install lib(linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libboost-test-dev -y

      - name: Install lib(Windows)
        if: runner.os == "Windows"
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: '2024.07.12'
          vcpkgArguments: 'boost-test'

      # - name: 

      - name: Configure CMake
        run: make -B build -DCMAKE_BUILD_TYPE=Release ${{ runner.os == 'Windows' && '-DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake' || '' }}

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-${{ runner.os }}
          path: build/myapp && build/Release/myapp.exe
      
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v4    
        with:
          path: artifact

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/myapp-Linux/myapp && artifacts/myapp-Windows/myapp.exe
          tag_name: 1.0.${{ github.run_number }}
          body: "Release 1.0.${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
